# https://testdriven.io/blog/running-flask-on-kubernetes/#minikube
# in a real deployment, this file would be git ignored, but because this is for demonstration purposes, I'm leaving it in

apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  user: cHNxbGFkbWlu
  password: dkdSWEFXZDdIS0FwYU5RNHp6UC5hcjlOdUJnVGQ2eFBHNHNEQkxQZHlORGRfVURu
